language: android

env:
    global:
    - MSDKUI_APP_ID_ANDROID=$MSDKUI_APP_ID_ANDROID
    - MSDKUI_APP_TOKEN_ANDROID=$MSDKUI_APP_TOKEN_ANDROID
    - MSDKUI_APP_LICENSE_ANDROID=$MSDKUI_APP_LICENSE_ANDROID
    - AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY
    - SDK_VER=$SDK_VER
    - SDK_URL=$SDK_URL

android:
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
    - pip install --user awscli

jobs:
  include:
    - stage: fetch HERE-SDK
        script:
            aws s3 cp s3://$SDK_URL/$SDK_VER $HOME
            echo "Copy SDK"
            cp $HOME/$SDK_VER $HOME/MSDKUIKit/libs/HERE-sdk.aar
            cp $HOME/$SDK_VER $HOME/MSDKUIDemo/libs/HERE-sdk.aar
    - stage: Library unit tests
        script:
            echo "Library Run analysis tools,run Tests and assembleRelease"
            ./gradlew clean \
            :MSDKUILib:check -x test \
            :MSDKUILib:testDebugUnitTest \
            :MSDKUILib:assembleRelease -x test
            cp $HOME/MSDKUIKit/MSDKUILib/build/outputs/aar/MSDKUILib-release.aar \
            $HOME/MSDKUIDemo/libs/MSDKUILib.aar
    - stage: Demo app tests
        script:
            echo "DemoApp Run analysis tools,run Tests and assembleRelease"
            cp $HOME/MSDKUIKit/MSDKUILib/build/outputs/aar/MSDKUILib-release.aar \
            $HOME/MSDKUIDemo/libs/MSDKUILib.aar
            cd $HOME/MSDKUIDemo
            ./gradlew clean
            :MSDKUIApp:check -x test
            :MSDKUIApp:test
